version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: latti_postgres
    environment:
      POSTGRES_DB: latti_stock
      POSTGRES_USER: latti_user
      POSTGRES_PASSWORD: latti_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - latti_network
    restart: unless-stopped

  # Backend Spring Boot
  backend:
    build: .
    container_name: latti_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/latti_stock
      SPRING_DATASOURCE_USERNAME: latti_user
      SPRING_DATASOURCE_PASSWORD: latti_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
    networks:
      - latti_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  latti_network:
    driver: bridge
